version: 2
jobs:
  build-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install setuptools --upgrade
            pip install numpy==1.19.4
            python3 setup.py develop
      - save_cache:
          key: deps-{{ checksum "setup.py" }}
          paths:
            - venv
      - run:
          command: |
            . venv/bin/activate
            pip install -r requirements/requirements.txt
            pip install -r requirements/requirements_test.txt
            flake8 ./pylivetrader
            pytest

  build-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install setuptools --upgrade
            python3 setup.py develop
      - save_cache:
          key: deps-{{ checksum "setup.py" }}
          paths:
            - venv
      - run:
          command: |
            . venv/bin/activate
            pip install -r requirements/requirements.txt
            pip install -r requirements/requirements_test.txt
            flake8 ./pylivetrader
            pytest

workflows:
  version: 2
  build:
    jobs:
      - build-python36
